title: Plateforme de Protection des Lanceurs d'Alerte en Afrique
email: info@pplaaf.org
url: "https://pplaaf.org"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  ngos-en:
  board-en:
  journalists-en:
  management-en:
  studies-en:
  management-en:
  profiles-en:
    output: true
    permalink: :name.html
  studies-en:
    output: true
    permalink: :name.html
  ngos-fr:
  board-fr:
  journalists-fr:
  management-fr:
  profiles-fr:
    output: true
    permalink: fr/:name.html
  studies-fr:
    output: true
    permalink: fr/:name.html
  # ngos-pt:
  board-pt:
  journalists-pt:
  management-pt:
  profiles-pt:
    output: true
    permalink: pt/:name.html
  # studies-fr:
  #   output: true
  #   permalink: fr/:name.html